import { useState } from "react";
import { ArrowLeft, Bug, Check, RefreshCw, Trophy, X } from "lucide-react";
import { initialPlayers, powers, r1Prompt, r2Prompt, finalPrompt, type Power } from "../game/data";
import { AnswerBox, CTA, CopyButton, GameTitle, Header, HostBubble, Input, PaperCard, PromptCard, Shell, VoteCard, Zap, colors } from "../components/GameUI";

type Phase = "home" | "join" | "lobby" | "prompt" | "answer" | "answerLocked" | "vote" | "locked" | "results" | "power" | "target" | "reveal" | "r2prompt" | "r2answer" | "r2answerLocked" | "r2vote" | "r2locked" | "r2results" | "finalIntro" | "finalAnswer" | "finalAnswerLocked" | "finalVote" | "finalLocked" | "gameOver" | "error";
const names = ["Amogh", "Priya", "Rahul", "Sarah"];

export default function GameShell() {
  const [phase, setPhase] = useState<Phase>("home");
  const [players, setPlayers] = useState(initialPlayers.slice(0, 2));
  const [answer, setAnswer] = useState("");
  const [vote, setVote] = useState<number | null>(null);
  const [power, setPower] = useState<Power | null>(null);
  const [target, setTarget] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [joinCode, setJoinCode] = useState("");
  const [joinName, setJoinName] = useState("");
  const [joinError, setJoinError] = useState("");

  const resetRound = () => { setAnswer(""); setVote(null); };
  const advance = (next: Phase) => { resetRound(); setPhase(next); };
  const copyLink = () => { setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  const addPlayer = () => { if (players.length < 4) setPlayers(initialPlayers.slice(0, players.length + 1)); };
  const start = () => setPhase("prompt");
  const goJoin = () => { if (!joinCode.trim() || !joinName.trim()) { setJoinError("Enter a meeting code and your name."); return; } setPlayers(initialPlayers); setPhase("lobby"); };

  if (phase === "home") return <Shell testId="screen-home"><div className="flex flex-1 flex-col justify-between py-16"><div className="text-center"><GameTitle className="text-7xl sm:text-8xl">UNHINGED</GameTitle><div className="mx-auto mt-3 h-1 w-4/5" style={{ background: colors.pink, boxShadow: "3px 3px 0 #000" }} /><p className="mt-5 font-display text-lg uppercase tracking-wide">The corporate roast game</p><p className="mt-1 text-sm text-white/50">Say what you can't say at work.</p><div className="mt-8 flex justify-center gap-3">{[colors.pink, colors.cyan, colors.green, colors.yellow].map(c => <i key={c} className="h-3 w-3 border-2 border-black" style={{ background: c }} />)}</div></div><div className="space-y-4"><CTA testId="button-create-game" onClick={() => setPhase("lobby")}>CREATE GAME</CTA><CTA testId="button-join-game" color="cyan" onClick={() => setPhase("join")}>JOIN GAME</CTA><button data-testid="button-debug-error" type="button" onClick={() => setPhase("error")} className="mx-auto block text-xs text-white/40 underline"><Bug size={12} className="mr-1 inline" /> prototype connection demo</button></div></div></Shell>;

  if (phase === "join") return <Shell testId="screen-join"><div className="flex flex-1 flex-col"><button data-testid="button-back-home" onClick={() => setPhase("home")} className="mt-7 flex w-fit items-center gap-2 text-sm font-bold"><ArrowLeft size={18} /> BACK</button><GameTitle className="mt-10 text-5xl">JOIN A<br />GAME</GameTitle><div className="mt-10 space-y-5"><label className="block font-display uppercase">Enter the game code<Input data-testid="input-game-code" value={joinCode} onChange={e => setJoinCode(e.target.value.toUpperCase())} placeholder="7FKP" /></label><label className="block font-display uppercase">Your name<Input data-testid="input-player-name" value={joinName} onChange={e => setJoinName(e.target.value)} placeholder="Amogh" /></label>{joinError && <p data-testid="text-join-error" className="font-bold text-pink-400">{joinError}</p>}<CTA testId="button-submit-join" onClick={goJoin}>JOIN MEETING</CTA><div className="py-4 text-center text-sm text-white/50">──────── OR ────────</div><CTA testId="button-scan-qr" color="cyan" onClick={() => { setJoinCode("7FKP"); setJoinName("Amogh"); }}>SCAN QR</CTA></div></div></Shell>;

  if (phase === "lobby") return <Shell testId="screen-lobby"><div className="flex flex-1 flex-col"><GameTitle className="mt-10 text-6xl">BOARD<br />ROOM</GameTitle><p className="mt-2 italic text-white/60">Nobody knows why we're here.</p><div className="mt-6 flex items-center justify-between border-2 border-black p-4" style={{ background: "#1a1a33", boxShadow: "4px 4px 0 #fff" }}><div><p className="text-xs uppercase tracking-widest text-white/50">Meeting ID</p><p data-testid="text-room-code" className="font-display text-3xl tracking-[.2em]">7FKP</p></div><CopyButton onCopy={copyLink} copied={copied} /></div><p data-testid="status-player-count" className="mt-4 font-display text-sm" style={{ color: colors.pink }}>{players.length} / 8 PEOPLE IN</p><PaperCard className="mt-3 p-0"><p className="border-b-2 border-black p-3 font-display text-xs uppercase tracking-widest">Players</p>{players.map((p, i) => <div data-testid={`row-player-${p.id}`} key={p.id} className="flex items-center gap-3 border-b border-black/10 p-3"><span className="h-3 w-3 rounded-full border-2 border-black" style={{ background: p.color }} /><span className="min-w-0 flex-1 break-words font-bold">{p.name}</span>{i === 0 && <span className="border border-black bg-yellow-300 px-2 text-xs font-bold text-black">YOU</span>}</div>)}{players.length < 3 && <button data-testid="button-add-player" type="button" onClick={addPlayer} className="w-full p-3 text-left text-sm font-bold text-slate-500">＋ add a demo employee</button>}</PaperCard><PaperCard className="mt-4"><p className="font-display text-xs uppercase tracking-widest">HOW TO PLAY</p><p className="mt-2 font-bold leading-relaxed">Answer the prompt.<br />Vote for your favourite.<br />Win points. Cause problems.</p></PaperCard><div className="mt-auto pt-5"><p data-testid="status-start-readiness" className="mb-3 text-center text-sm font-bold">{players.length < 3 ? "Waiting for 1 more employee..." : "Ready when you are."}</p><CTA testId="button-start-meeting" onClick={start} disabled={players.length < 3}>START MEETING</CTA></div></div></Shell>;

  if (phase === "prompt") return <Shell testId="screen-prompt"><Header round="ROUND 1" right={<span className="font-display text-3xl text-yellow-300">00:38</span>} /><div className="flex flex-1 flex-col justify-center"><PromptCard prompt={r1Prompt} context={'Your manager says: "Can we jump on a quick call?"'} /><p className="mt-5 text-center text-sm text-white/50">Be honest. Be ruthless. Be professional.</p><div className="mt-6"><CTA testId="button-start-answer" onClick={() => setPhase("answer")}>ANSWER NOW</CTA></div></div></Shell>;

  if (phase === "answer" || phase === "r2answer" || phase === "finalAnswer" || phase === "answerLocked" || phase === "r2answerLocked" || phase === "finalAnswerLocked") { const locked = phase.includes("Locked"); const base = phase.replace("Locked", ""); const round = base === "r2answer" ? "ROUND 2" : base === "finalAnswer" ? "FINAL ROUND" : "ROUND 1"; const prompt = base === "r2answer" ? r2Prompt : base === "finalAnswer" ? finalPrompt : r1Prompt; return <Shell testId={`screen-${phase}`}><Header round={round} right={<span className="font-display text-3xl text-yellow-300">00:38</span>} />{base === "r2answer" && power && <div className="mb-4 border-2 border-black p-3 text-black" style={{ background: colors.pink }}><p className="font-display text-xs">POWER PLAY</p><p className="font-display uppercase"> {power.id === "word" ? "USE THE WORD" : power.title}: {power.value}</p></div>}<PromptCard prompt={prompt} context={base === "answer" ? 'Your manager says: "Can we jump on a quick call?"' : undefined} /><AnswerBox value={answer} onChange={setAnswer} locked={locked} onLock={() => setPhase(base === "answer" ? "answerLocked" : base === "r2answer" ? "r2answerLocked" : "finalAnswerLocked")} />{locked && <div className="mt-5"><CTA testId="button-continue-to-vote" onClick={() => setPhase(base === "answer" ? "vote" : base === "r2answer" ? "r2vote" : "finalVote")}>CONTINUE</CTA></div>}</Shell>; }

  if (phase === "vote" || phase === "r2vote" || phase === "finalVote") { const final = phase === "finalVote"; const round = phase === "r2vote" ? "ROUND 2" : final ? "THE FINAL VOTE" : "ROUND 1"; const options = final ? ["A bold rebrand nobody asked for.", "We failed upward with confidence.", "A strategic pause with excellent snacks."] : phase === "r2vote" ? ["I think we're aligned on the synergy here.", "We pivoted before the market could panic."] : ["Last two hours.", "My entire afternoon."]; return <Shell testId={`screen-${phase}`}><Header round={round} /><h2 className="font-display text-3xl uppercase text-yellow-300">{final ? "PICK THE ANSWER THAT DESERVES THE BOARDROOM MIC." : "WHICH RESPONSE IS BETTER?"}</h2><div className="mt-6 flex flex-1 flex-col gap-5">{options.map((text, i) => <VoteCard key={text} index={i} letter={String.fromCharCode(65 + i)} text={text} selected={vote === i} onClick={() => setVote(i)} />)}</div><div className="mt-5 pb-4"><CTA testId="button-submit-vote" onClick={() => setPhase(final ? "finalLocked" : phase === "r2vote" ? "r2locked" : "locked")} disabled={vote === null}>LOCK MY VOTE</CTA><p className="mt-3 text-center text-xs text-white/50">You can't vote for yourself.</p></div></Shell>; }

  if (phase === "locked" || phase === "r2locked" || phase === "finalLocked") { const final = phase === "finalLocked"; return <Shell testId={`screen-${phase}`}><div className="flex flex-1 flex-col items-center justify-center text-center"><Check className="h-16 w-16 text-green-300" /><GameTitle className="mt-5 text-5xl">VOTE<br />LOCKED</GameTitle><p className="mt-5 text-lg font-bold">Waiting for everyone...</p><div className="mt-8 flex gap-3">{players.map(p => <span key={p.id} className="h-4 w-4 rounded-full border-2 border-black" style={{ background: colors.green }} />)}</div><div className="mt-auto w-full pb-4"><CTA testId="button-continue-after-vote" onClick={() => setPhase(final ? "gameOver" : phase === "r2locked" ? "r2results" : "results")}>SHOW RESULTS</CTA></div></div></Shell>; }

  if (phase === "results" || phase === "r2results") { const round2 = phase === "r2results"; return <Shell testId={`screen-${phase}`}><Header round={`${round2 ? "ROUND 2" : "ROUND 1"} · RESULTS`} /><div className="flex flex-1 flex-col items-center pt-6 text-center"><div className="text-6xl"><Trophy /></div><GameTitle className="mt-3 text-5xl">WINNER!</GameTitle><h2 data-testid="text-winner" className="mt-2 font-display text-5xl">PRIYA</h2><p className="mt-3 border-2 border-black px-4 py-2 font-display text-3xl text-green-300" style={{ boxShadow: "3px 3px 0 #fff" }}>+{round2 ? "600" : "400"} PTS</p><PaperCard className="mt-8 w-full text-left"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Winning answer</p><p className="mt-2 font-display text-2xl">"{round2 ? "I think we're aligned on the synergy here." : "My entire afternoon."}"</p><p className="mt-2 text-sm text-slate-500">Voted by 4 people.</p></PaperCard><HostBubble>{round2 ? "Nothing says accountability like the word synergy." : "Apparently four people needed their afternoon back."}</HostBubble><div className="mt-auto w-full pb-4"><CTA testId="button-next-results" onClick={() => setPhase(round2 ? "finalIntro" : "power")}>NEXT</CTA></div></div></Shell>; }

  if (phase === "power") return <Shell testId="screen-power-select"><GameTitle className="mt-10 text-6xl">YOU WON.</GameTitle><h2 className="mt-2 font-display text-3xl">NOW CAUSE PROBLEMS.</h2><p className="mt-4 inline-block border-2 border-black px-3 py-2 font-display text-sm text-black" style={{ background: colors.pink }}>+2 ABILITY POINTS</p><p className="mt-5 font-bold">Choose your power.</p><div className="mt-5 flex flex-1 flex-col gap-4">{powers.map(p => <button data-testid={`button-power-${p.id}`} key={p.id} type="button" onClick={() => setPower(p)} className="flex w-full items-center gap-4 border-2 border-black p-4 text-left text-black" style={{ background: power?.id === p.id ? colors.pink : colors.paper, boxShadow: power?.id === p.id ? `4px 4px 0 ${colors.pink}` : "4px 4px 0 #000" }}><span className="flex h-12 w-12 items-center justify-center border-2 border-black bg-yellow-300 text-black"><Zap /></span><span className="min-w-0 flex-1"><b className="font-display">{p.title}</b><small className="block break-words text-slate-600">{p.description}</small></span><b className="font-display">{p.cost} PT</b></button>)}</div><div className="pb-4 pt-5"><CTA testId="button-use-power" onClick={() => setPhase("target")} disabled={!power}>USE POWER</CTA></div></Shell>;

  if (phase === "target") return <Shell testId="screen-target"><GameTitle className="mt-12 text-6xl">WHO GETS IT?</GameTitle><p className="mt-4 text-white/70">Pick an opponent to carry the chaos.</p><div className="mt-8 flex flex-col gap-3">{players.filter(p => p.id !== "you").map(p => <button data-testid={`button-target-${p.id}`} key={p.id} onClick={() => setTarget(p.id)} className="border-2 border-black p-4 text-left font-display text-xl text-black" style={{ background: target === p.id ? colors.pink : colors.paper, boxShadow: "3px 3px 0 #000" }}>{p.name}{target === p.id && <Check className="float-right" />}</button>)}</div><div className="mt-auto pb-4 pt-6"><CTA testId="button-confirm-power" onClick={() => setPhase("reveal")} disabled={!target}>CONFIRM POWER</CTA></div></Shell>;

  if (phase === "reveal") return <Shell testId="screen-power-reveal"><p className="mt-10 font-display text-xs tracking-widest text-white/50">YOUR POWER</p><div className="flex flex-1 items-center"><PaperCard className="w-full text-center" accent="#fff"><p className="font-display text-2xl" style={{ color: colors.pink }}>{power?.title}</p><p className="mt-6 text-xs font-bold uppercase tracking-widest text-slate-500">YOUR TARGET MUST {power?.id === "persona" ? "ANSWER AS" : power?.id === "word" ? "USE" : "ANSWER USING"}</p><h2 data-testid="text-power-value" className="mt-3 break-words border-2 border-black bg-yellow-300 p-4 font-display text-3xl">{power?.value}</h2><p className="mt-5 italic text-slate-600">Good luck explaining that.</p></PaperCard></div><div className="pb-4"><CTA testId="button-start-round-two" onClick={() => setPhase("r2prompt")}>LET'S GO</CTA></div></Shell>;

  if (phase === "r2prompt") return <Shell testId="screen-round-two-prompt"><div className="flex flex-1 flex-col items-center justify-center text-center"><GameTitle className="text-6xl">ROUND 2</GameTitle><p className="mt-5 font-display text-2xl">HIGHER STAKES.<br />LOWER MATURITY.</p><PaperCard className="mt-8 w-full text-left"><p className="font-display text-xs uppercase tracking-widest text-slate-500">Prompt</p><p className="mt-3 font-display text-xl">{r2Prompt}</p></PaperCard><div className="mt-auto w-full pb-4 pt-8"><CTA testId="button-start-round-two-answer" onClick={() => setPhase("r2answer")}>ANSWER NOW</CTA></div></div></Shell>;

  if (phase === "finalIntro") return <Shell testId="screen-final-intro" accent={colors.pink}><div className="flex flex-1 flex-col items-center justify-center text-center"><p className="font-display text-xs tracking-widest text-white/50">★ ★ ★ LAST CHANCE ★ ★ ★</p><GameTitle className="mt-6 text-7xl">FINAL<br />ROUND</GameTitle><div className="mt-6 flex gap-2">{[1,2,3,4,5].map(i => <span key={i} className="h-4 w-4 border-2 border-black bg-yellow-300" />)}</div><p className="mt-6 font-display text-2xl">EVERYONE ANSWERS</p><PaperCard className="mt-6 w-full text-left" accent={colors.yellow}><p className="font-display text-lg">{finalPrompt}</p></PaperCard><p className="mt-4 text-sm">Everyone answers now.</p><div className="mt-auto w-full pb-4 pt-6"><CTA testId="button-start-final" onClick={() => setPhase("finalAnswer")}>LET'S GO</CTA></div></div></Shell>;

  if (phase === "gameOver") return <Shell testId="screen-final-results"><GameTitle className="mt-10 text-4xl">THE QUARTERLY<br />RESULTS</GameTitle><div className="mt-8 space-y-3">{[["1","PRIYA","2,840"],["2","RAHUL","2,510"],["3","AMOGH","1,920"],["4","SARAH","1,640"]].map(([medal, name, score], i) => <div data-testid={`row-leaderboard-${i}`} key={name} className="flex items-center gap-3 border-2 border-black p-3 text-black" style={{ background: i === 0 ? colors.yellow : colors.paper, boxShadow: "3px 3px 0 #000" }}><span className="text-xl font-display">{medal}</span><span className="min-w-0 flex-1 break-words font-display">{name}</span><span className="font-display">{score} pts</span></div>)}</div><div className="mt-6 border-2 border-black p-4 text-black" style={{ background: colors.pink, boxShadow: "4px 4px 0 #000" }}><p className="font-display text-xs">YOUR CORPORATE PERSONA</p><p className="mt-1 font-display text-2xl">STRATEGIC MENACE</p><p className="text-sm italic">Most likely to say "noted" while plotting revenge.</p></div><HostBubble>Congratulations. Nobody learned anything.</HostBubble><div className="mt-auto space-y-3 pb-4 pt-6"><CTA testId="button-play-again" onClick={() => { setPlayers(initialPlayers.slice(0, 2)); setPhase("lobby"); }}>PLAY AGAIN</CTA><button data-testid="button-share-game" onClick={copyLink} className="w-full py-3 font-display text-white underline">{copied ? "LINK COPIED!" : "SHARE GAME"}</button></div></Shell>;

  return <Shell testId="screen-error"><div className="flex flex-1 flex-col items-center justify-center text-center"><X className="h-20 w-20 text-pink-400" /><GameTitle className="mt-6 text-6xl">UH OH.</GameTitle><h2 className="mt-3 font-display text-3xl">CONNECTION LOST.</h2><p className="mt-4 max-w-xs text-white/70">Refresh the page to rejoin the meeting.</p><button data-testid="button-refresh" onClick={() => setPhase("home")} className="mt-8 flex items-center gap-2 border-2 border-black bg-yellow-300 px-6 py-4 font-display text-black" style={{ boxShadow: "4px 4px 0 #000" }}><RefreshCw size={18} /> REFRESH</button></div></Shell>;
}