import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Copy, RefreshCw, Trophy, X, Zap } from "lucide-react";
import { AnswerBox, CTA, GameTitle, Header, HostBubble, Input, PaperCard, PromptCard, Shell, VoteCard, colors } from "../components/GameUI";
import { AnswerReview } from "../components/AnswerReview";
import { useGameSocket } from "../game/useGameSocket";
import type { PowerType, Snapshot } from "../game/types";
import { Checkbox } from "@workspace/neo-brutalism-ui/components/checkbox";

const powers: { id: PowerType; title: string; description: string; cost: number }[] = [
  { id: "word", title: "USE THIS WORD", description: "Force a word into an answer.", cost: 1 },
  { id: "persona", title: "ANSWER AS A...", description: "Change the personality.", cost: 1 },
  { id: "emoji", title: "EMOJI ONLY", description: "No words allowed.", cost: 2 },
];

export default function GameShell() {
  const game = useGameSocket();
  const { snapshot: s, error } = game;
  const [screen, setScreen] = useState<"home" | "create" | "join">(() => new URLSearchParams(window.location.search).has("room") ? "join" : "home");
  const [name, setName] = useState("");
  const [code, setCode] = useState(() => new URLSearchParams(window.location.search).get("room")?.toUpperCase() || "");
  const [answer, setAnswer] = useState("");
  const [selectedPower, setSelectedPower] = useState<PowerType | null>(null);
  const [target, setTarget] = useState("");
  const [copied, setCopied] = useState(false);
  useEffect(() => { if (s) { setScreen("home"); setAnswer(""); setSelectedPower(null); setTarget(""); } }, [s?.phase, s?.round]);
  const assignment = useMemo(() => s?.assignments?.find(a => !a.answer), [s?.assignments]);
  const group = useMemo(() => s?.voteGroups?.find(g => !g.voted), [s?.voteGroups]);
  const isHost = Boolean(s && s.me?.id === s.hostId);
  const results = s?.results ?? game.lastResults;
  const isWinner = Boolean(s && s.me?.id === results?.winnerId);
  const copyInvite = async () => {
    if (!s) return;
    await navigator.clipboard?.writeText(`${window.location.origin}?room=${s.roomCode}`);
    setCopied(true); window.setTimeout(() => setCopied(false), 1800);
  };
  const submitAnswer = () => {
    if (!assignment || !answer.trim()) return;
    const [pairId, question] = assignment.assignmentId.split(":");
    game.answer({ text: answer, ...(pairId !== "final" ? { pairId, question: Number(question) } : {}) });
    setAnswer("");
  };

  if (game.reconnecting) return <Shell testId="screen-reconnecting"><div className="flex flex-1 flex-col items-center justify-center text-center"><RefreshCw className="h-20 w-20 animate-spin text-cyan-300" /><GameTitle className="mt-6 text-5xl">RECONNECTING</GameTitle><p className="mt-4 max-w-xs text-white/70">Holding your seat in the meeting…</p></div></Shell>;
  if (game.disconnected) return <Shell testId="screen-error"><div className="flex flex-1 flex-col items-center justify-center text-center"><X className="h-20 w-20 text-pink-400" /><GameTitle className="mt-6 text-6xl">UH OH.</GameTitle><p className="mt-4 max-w-xs text-white/70">{error || "Unable to reconnect. Refresh to rejoin."}</p><button data-testid="button-refresh" onClick={() => window.location.reload()} className="mt-8 flex items-center gap-2 border-2 border-black bg-yellow-300 px-6 py-4 font-display text-black"><RefreshCw size={18} /> REFRESH</button></div></Shell>;
  if (!s && screen === "home") return <Shell testId="screen-home"><div className="flex flex-1 flex-col justify-between py-16"><div className="text-center"><GameTitle className="text-7xl sm:text-8xl">UNHINGED</GameTitle><div className="mx-auto mt-3 h-1 w-4/5" style={{ background: colors.pink, boxShadow: "3px 3px 0 #000" }} /><p className="mt-5 font-display text-lg uppercase tracking-wide">The corporate roast game</p><p className="mt-1 text-sm text-white/50">Say what you can't say at work.</p><div className="mt-8 flex justify-center gap-3">{[colors.pink, colors.cyan, colors.green, colors.yellow].map(c => <i key={c} className="h-3 w-3 border-2 border-black" style={{ background: c }} />)}</div></div><div className="space-y-4"><CTA testId="button-create-game" onClick={() => setScreen("create")}>CREATE GAME</CTA><CTA testId="button-join-game" color="cyan" onClick={() => setScreen("join")}>JOIN GAME</CTA>{error && <p className="text-center font-bold text-pink-400">{error}</p>}</div></div></Shell>;
  if (!s && screen === "create") return <Shell testId="screen-create"><button data-testid="button-back-home" onClick={() => setScreen("home")} className="mt-7 flex w-fit items-center gap-2 text-sm font-bold"><ArrowLeft size={18} /> BACK</button><GameTitle className="mt-10 text-5xl">CREATE A<br />GAME</GameTitle><label className="mt-10 block font-display uppercase">Host name<Input data-testid="input-host-name" value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></label>{error && <p className="mt-3 font-bold text-pink-400">{error}</p>}<div className="mt-auto pb-4"><CTA testId="button-submit-create" onClick={() => game.create(name)} disabled={!name.trim()}>CREATE ROOM</CTA></div></Shell>;
  if (!s && screen === "join") return <Shell testId="screen-join"><button data-testid="button-back-home" onClick={() => setScreen("home")} className="mt-7 flex w-fit items-center gap-2 text-sm font-bold"><ArrowLeft size={18} /> BACK</button><GameTitle className="mt-10 text-5xl">JOIN A<br />GAME</GameTitle><div className="mt-10 space-y-5"><label className="block font-display uppercase">Enter the game code<Input data-testid="input-game-code" value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="7FKP" /></label><label className="block font-display uppercase">Your name<Input data-testid="input-player-name" value={name} onChange={e => setName(e.target.value)} placeholder="Your name" /></label>{error && <p data-testid="text-join-error" className="font-bold text-pink-400">{error}</p>}<CTA testId="button-submit-join" onClick={() => game.join(code, name)} disabled={!code.trim() || !name.trim()}>JOIN MEETING</CTA></div></Shell>;
  if (!s) return <Shell testId="screen-error"><div className="flex flex-1 flex-col items-center justify-center text-center"><X className="h-20 w-20 text-pink-400" /><GameTitle className="mt-6 text-6xl">UH OH.</GameTitle><p className="mt-4 max-w-xs text-white/70">{error || "Connection lost."}</p><button data-testid="button-refresh" onClick={() => window.location.reload()} className="mt-8 flex items-center gap-2 border-2 border-black bg-yellow-300 px-6 py-4 font-display text-black"><RefreshCw size={18} /> REFRESH</button></div></Shell>;

  if (s.phase === "lobby") return <Shell testId="screen-lobby"><div className="flex flex-1 flex-col"><GameTitle className="mt-10 text-6xl">BOARD<br />ROOM</GameTitle><p className="mt-2 italic text-white/60">Nobody knows why we're here.</p><div className="mt-6 flex items-center justify-between border-2 border-black p-4" style={{ background: "#1a1a33", boxShadow: "4px 4px 0 #fff" }}><div><p className="text-xs uppercase tracking-widest text-white/50">Meeting ID</p><p data-testid="text-room-code" className="font-display text-3xl tracking-[.2em]">{s.roomCode}</p></div><button data-testid="button-copy-link" onClick={copyInvite} className="flex items-center gap-2 border-2 border-black bg-cyan-300 px-3 py-2 font-display text-black">{copied ? "COPIED!" : "COPY LINK"} <Copy size={16} /></button></div><p data-testid="status-player-count" className="mt-4 font-display text-sm" style={{ color: colors.pink }}>{s.players.length} / 8 PEOPLE IN</p><PaperCard className="mt-3 p-0"><p className="border-b-2 border-black p-3 font-display text-xs uppercase tracking-widest">Players</p>{s.players.map((p) => <div data-testid={`row-player-${p.id}`} key={p.id} className="flex items-center gap-3 border-b border-black/10 p-3"><span className="h-3 w-3 rounded-full border-2 border-black bg-cyan-300" /><span className="min-w-0 flex-1 break-words font-bold">{p.name}</span>{p.id === s.hostId && <span className="border border-black bg-yellow-300 px-2 text-xs font-bold text-black">HOST</span>}</div>)}</PaperCard><PaperCard className="mt-4"><div className="font-display text-sm uppercase">Question settings</div>{isHost ? <Checkbox data-testid="checkbox-avoid-recent-prompts" className="mt-2" color="cyan" label="Avoid recent questions" checked={s.avoidRecentPrompts} onChange={e => game.setAvoidRecentPrompts(e.target.checked)} /> : <p className="mt-2 text-sm">{s.avoidRecentPrompts ? "Recent questions will be avoided" : "Recent questions may repeat"}</p>}<p className="mt-2 text-xs">Fresh questions come first across rematches. Older ones return if needed.</p></PaperCard><div className="mt-auto pt-5">{error && <p className="mb-3 text-center font-bold text-pink-400">{error}</p>}{isHost ? <CTA testId="button-start-meeting" onClick={game.start} disabled={s.players.length < 3}>START MEETING</CTA> : <p data-testid="status-start-readiness" className="text-center text-sm font-bold">Waiting for the host to start…</p>}</div></div></Shell>;
  if (s.phase === "answering") return <Shell testId="screen-answering"><RoundHeader round={`ROUND ${s.round}`} deadline={s.deadline} /><div className="flex flex-1 flex-col">{s.modifier && <PaperCard className="mb-4"><p className="font-display text-xs text-pink-500">POWER PLAY</p><p className="mt-1 font-display uppercase">{s.modifier.type}: {s.modifier.value}</p></PaperCard>}{assignment ? <><PromptCard prompt={assignment.prompt} /><p className="mt-4 text-center text-sm text-white/60">Answer {s.progress.submitted + 1} of {s.progress.required}</p><AnswerBox value={answer} onChange={setAnswer} locked={false} onLock={submitAnswer} /></> : <Waiting text={`Waiting for everyone… ${s.progress.submitted}/${s.progress.required} submitted`} />}</div></Shell>;
  if (s.phase === "voting") return <Shell testId="screen-voting"><RoundHeader round={`ROUND ${s.round} · VOTE`} deadline={s.deadline} /><h2 className="font-display text-3xl uppercase text-yellow-300">WHICH RESPONSE DESERVES THE MIC?</h2><div className="mt-6 flex flex-1 flex-col gap-5">{group ? group.answers.map((a, i) => <VoteCard key={a.id} index={i} letter={String.fromCharCode(65 + i)} text={a.text} selected={false} onClick={() => game.vote(a.id)} />) : <Waiting text={`Waiting for everyone… ${s.progress.submitted}/${s.progress.required} votes`} />}</div><AnswerReview answers={s.answerList ?? []} viewerId={s.me?.id} /></Shell>;
  if (s.phase === "results") return <ResultsScreen s={s} isHost={isHost} isWinner={isWinner} onNext={game.next} />;
  if (s.phase === "powerSelect") return isWinner ? <PowerSelect selected={selectedPower} setSelected={setSelectedPower} target={target} setTarget={setTarget} players={s.players.filter(p => p.id !== s.me?.id)} onUse={() => selectedPower && target && game.power(selectedPower, target)} /> : <Waiting text="The winner is choosing a power…" />;
  if (s.phase === "powerReveal") return <Shell testId="screen-power-reveal"><p className="mt-10 font-display text-xs tracking-widest text-white/50">POWER PLAY</p><div className="flex flex-1 items-center"><PaperCard className="w-full text-center"><Zap className="mx-auto text-pink-500" /><p className="mt-3 font-display text-2xl text-pink-500">{s.modifier?.type.toUpperCase() || "CHAOS ASSIGNED"}</p><h2 data-testid="text-power-value" className="mt-3 break-words border-2 border-black bg-yellow-300 p-4 font-display text-3xl">{s.modifier?.value || "Classified until the next round."}</h2></PaperCard></div><div className="pb-4">{isHost || isWinner ? <CTA testId="button-start-round-two" onClick={game.next}>CONTINUE</CTA> : <Waiting text="Waiting for the host or winner…" />}</div></Shell>;
  if (s.phase === "gameOver") return <GameOver s={s} isHost={isHost} onRematch={game.rematch} />;
  return <Waiting text="Waiting for the next round…" />;
}

function Waiting({ text }: { text: string }) { return <div className="flex flex-1 flex-col items-center justify-center text-center"><Check className="h-16 w-16 text-green-300" /><GameTitle className="mt-5 text-4xl">LOCKED</GameTitle><p className="mt-5 text-lg font-bold">{text}</p></div>; }
function RoundHeader({ round, deadline }: { round: string; deadline?: number }) { const [now, setNow] = useState(Date.now()); useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 500); return () => window.clearInterval(id); }, []); const seconds = Math.max(0, Math.ceil(((deadline ?? now) - now) / 1000)); return <Header round={round} right={<span data-testid="text-timer" className="font-display text-3xl text-yellow-300">{String(Math.floor(seconds / 60)).padStart(2, "0")}:{String(seconds % 60).padStart(2, "0")}</span>} />; }
function ResultsScreen({ s, isHost, isWinner, onNext }: { s: Snapshot; isHost: boolean; isWinner: boolean; onNext: () => void }) {
  const r = s.results;
  const winner = s.players.find(p => p.id === r?.winnerId);
  const winningAnswer = r?.answers.filter(a => a.authorId === r.winnerId && a.submitted).sort((a, b) => b.votes - a.votes)[0];
  return <Shell testId="screen-results"><Header round={`ROUND ${s.round} · RESULTS`} /><div className="flex flex-1 flex-col items-center text-center"><Trophy className="mt-5 h-16 w-16 text-yellow-300" /><GameTitle className="mt-3 text-5xl">WINNER!</GameTitle><h2 data-testid="text-winner" className="mt-2 font-display text-4xl">{winner?.name}</h2>{winningAnswer && <PaperCard className="mt-8 w-full text-left"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Winning answer</p><p className="mt-2 break-words font-display text-2xl">"{winningAnswer.text}"</p><p className="mt-2 text-sm text-slate-500">Voted by {winningAnswer.votes} people.</p></PaperCard>}<AnswerReview answers={r?.answers ?? []} viewerId={s.me?.id} showVotes />{r?.roastLine && <HostBubble>{r.roastLine}</HostBubble>}<div className="mt-auto w-full pb-4 pt-6">{isHost || isWinner ? <CTA testId="button-next-results" onClick={onNext}>NEXT</CTA> : <Waiting text="Waiting for the host or winner…" />}</div></div></Shell>;
}
function PowerSelect({ selected, setSelected, target, setTarget, players, onUse }: any) { return <Shell testId="screen-power-select"><GameTitle className="mt-10 text-6xl">YOU WON.</GameTitle><h2 className="mt-2 font-display text-3xl">NOW CAUSE PROBLEMS.</h2><div className="mt-5 flex flex-1 flex-col gap-4">{powers.map(p => <button data-testid={`button-power-${p.id}`} key={p.id} type="button" onClick={() => setSelected(p.id)} className="flex w-full items-center gap-4 border-2 border-black p-4 text-left text-black" style={{ background: selected === p.id ? colors.pink : colors.paper, boxShadow: "4px 4px 0 #000" }}><Zap /><span className="min-w-0 flex-1"><b className="font-display">{p.title}</b><small className="block text-slate-600">{p.description}</small></span><b className="font-display">{p.cost} PT</b></button>)}<p className="font-display text-sm">TARGET</p>{players.map((p: any) => <button data-testid={`button-target-${p.id}`} key={p.id} onClick={() => setTarget(p.id)} className="border-2 border-black p-3 text-left font-display text-xl text-black" style={{ background: target === p.id ? colors.pink : colors.paper }}>{p.name}</button>)}</div><div className="pb-4 pt-5"><CTA testId="button-use-power" onClick={onUse} disabled={!selected || !target}>USE POWER</CTA></div></Shell>; }
function GameOver({ s, isHost, onRematch }: { s: Snapshot; isHost: boolean; onRematch: () => void }) { return <Shell testId="screen-final-results"><GameTitle className="mt-10 text-4xl">THE QUARTERLY<br />RESULTS</GameTitle><div className="mt-8 space-y-3">{s.results?.leaderboard?.map((p, i) => <div data-testid={`row-leaderboard-${i}`} key={p.id} className="flex items-center gap-3 border-2 border-black p-3 text-black" style={{ background: i === 0 ? colors.yellow : colors.paper, boxShadow: "3px 3px 0 #000" }}><span className="text-xl font-display">{i + 1}</span><span className="min-w-0 flex-1 break-words font-display">{p.name}</span><span className="font-display">{p.score} pts</span></div>)}</div><AnswerReview answers={s.results?.answers ?? []} viewerId={s.me?.id} showVotes /><HostBubble>{s.results?.roastLine || "Congratulations. Nobody learned anything."}</HostBubble><div className="mt-auto pb-4 pt-6">{isHost && <CTA testId="button-play-again" onClick={onRematch}>PLAY AGAIN</CTA>}</div></Shell>; }